#!/bin/sh

rm -f stdout
rm -f stderr
rm -f disk3.hex
rm -f disk3.out
rm -f disk3

./create_fs disk3
./amy_fs ../megainput6.txt > stdout 2>stderr

hexdump -C disk3 > disk3.hex

xxd -b -c 8 disk3 > disk3.out

echo "Done\n"
